# Generated by Django 4.2 on 2024-01-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cls', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
